-- Phase 1 production hardening for paid AI generation.
-- All identifiers are HMAC digests created by the application; no raw IP or email
-- address is stored in these tables.

create table if not exists public.ai_generation_jobs (
  idempotency_key text primary key check (char_length(idempotency_key) = 64),
  request_hash text not null check (char_length(request_hash) = 64),
  generation_kind text not null check (generation_kind in ('letter', 'visual_memory')),
  status text not null check (status in ('pending', 'succeeded', 'failed')),
  result jsonb,
  error_code text,
  attempt_count integer not null default 1 check (attempt_count > 0),
  lease_expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists ai_generation_jobs_active_idx
  on public.ai_generation_jobs (lease_expires_at)
  where status = 'pending';
create index if not exists ai_generation_jobs_cleanup_idx
  on public.ai_generation_jobs (updated_at);

create table if not exists public.ai_rate_limit_events (
  event_id bigint generated by default as identity primary key,
  generation_kind text not null check (generation_kind in ('letter', 'visual_memory')),
  subject_type text not null check (subject_type in ('ip', 'identity')),
  subject_hash text not null check (char_length(subject_hash) = 64),
  created_at timestamptz not null default now()
);

create index if not exists ai_rate_limit_events_lookup_idx
  on public.ai_rate_limit_events
  (generation_kind, subject_type, subject_hash, created_at desc);
create index if not exists ai_rate_limit_events_cleanup_idx
  on public.ai_rate_limit_events (created_at);

alter table public.ai_generation_jobs enable row level security;
alter table public.ai_rate_limit_events enable row level security;

create or replace function public.acquire_ai_generation_job(
  p_idempotency_key text,
  p_request_hash text,
  p_generation_kind text,
  p_ip_hash text,
  p_identity_hash text,
  p_window_seconds integer,
  p_ip_limit integer,
  p_identity_limit integer,
  p_daily_window_seconds integer,
  p_ip_daily_limit integer,
  p_identity_daily_limit integer,
  p_global_limit integer,
  p_lease_seconds integer,
  p_success_reuse_seconds integer
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_job public.ai_generation_jobs%rowtype;
  recent_count bigint;
  active_count bigint;
  retry_after integer;
begin
  if p_generation_kind not in ('letter', 'visual_memory')
     or p_window_seconds < 1 or p_ip_limit < 1 or p_global_limit < 1
     or p_daily_window_seconds < p_window_seconds or p_ip_daily_limit < p_ip_limit
     or p_lease_seconds < 1 or p_success_reuse_seconds < 1 then
    raise exception 'invalid ai generation guard configuration';
  end if;

  -- One cross-instance admission lock makes the global count and job claim atomic.
  perform pg_advisory_xact_lock(hashtextextended('soul-trace-ai-generation-admission', 0));

  select * into current_job
    from public.ai_generation_jobs
    where idempotency_key = p_idempotency_key
    for update;

  if found and current_job.request_hash <> p_request_hash then
    return jsonb_build_object('decision', 'conflict');
  end if;
  if found and current_job.status = 'pending'
     and current_job.lease_expires_at > now() then
    retry_after := greatest(1, ceil(extract(epoch from current_job.lease_expires_at - now()))::integer);
    return jsonb_build_object('decision', 'pending', 'retryAfter', least(retry_after, 30));
  end if;
  if found and current_job.status = 'succeeded'
     and current_job.updated_at > now() - make_interval(secs => p_success_reuse_seconds) then
    return jsonb_build_object('decision', 'succeeded', 'result', current_job.result);
  end if;

  select count(*) into recent_count
    from public.ai_rate_limit_events
    where generation_kind = p_generation_kind
      and subject_type = 'ip' and subject_hash = p_ip_hash
      and created_at > now() - make_interval(secs => p_window_seconds);
  if recent_count >= p_ip_limit then
    return jsonb_build_object('decision', 'rate_limited', 'retryAfter', p_window_seconds);
  end if;

  select count(*) into recent_count
    from public.ai_rate_limit_events
    where generation_kind = p_generation_kind
      and subject_type = 'ip' and subject_hash = p_ip_hash
      and created_at > now() - make_interval(secs => p_daily_window_seconds);
  if recent_count >= p_ip_daily_limit then
    return jsonb_build_object('decision', 'rate_limited', 'retryAfter', p_daily_window_seconds);
  end if;

  if p_identity_hash is not null and p_identity_limit > 0 then
    select count(*) into recent_count
      from public.ai_rate_limit_events
      where generation_kind = p_generation_kind
        and subject_type = 'identity' and subject_hash = p_identity_hash
        and created_at > now() - make_interval(secs => p_window_seconds);
    if recent_count >= p_identity_limit then
      return jsonb_build_object('decision', 'rate_limited', 'retryAfter', p_window_seconds);
    end if;
    select count(*) into recent_count
      from public.ai_rate_limit_events
      where generation_kind = p_generation_kind
        and subject_type = 'identity' and subject_hash = p_identity_hash
        and created_at > now() - make_interval(secs => p_daily_window_seconds);
    if p_identity_daily_limit > 0 and recent_count >= p_identity_daily_limit then
      return jsonb_build_object('decision', 'rate_limited', 'retryAfter', p_daily_window_seconds);
    end if;
  end if;

  select count(*) into active_count
    from public.ai_generation_jobs
    where status = 'pending' and lease_expires_at > now();
  if active_count >= p_global_limit then
    return jsonb_build_object('decision', 'busy', 'retryAfter', 15);
  end if;

  insert into public.ai_rate_limit_events(generation_kind, subject_type, subject_hash)
    values (p_generation_kind, 'ip', p_ip_hash);
  if p_identity_hash is not null and p_identity_limit > 0 then
    insert into public.ai_rate_limit_events(generation_kind, subject_type, subject_hash)
      values (p_generation_kind, 'identity', p_identity_hash);
  end if;

  insert into public.ai_generation_jobs(
    idempotency_key, request_hash, generation_kind, status, lease_expires_at
  ) values (
    p_idempotency_key, p_request_hash, p_generation_kind, 'pending',
    now() + make_interval(secs => p_lease_seconds)
  )
  on conflict (idempotency_key) do update set
    status = 'pending', result = null, error_code = null,
    attempt_count = public.ai_generation_jobs.attempt_count + 1,
    lease_expires_at = excluded.lease_expires_at,
    updated_at = now(), completed_at = null;

  return jsonb_build_object('decision', 'acquired');
end;
$$;

create or replace function public.complete_ai_generation_job(
  p_idempotency_key text,
  p_request_hash text,
  p_result jsonb
) returns boolean
language sql
security definer
set search_path = public
as $$
  update public.ai_generation_jobs
    set status = 'succeeded', result = p_result, error_code = null,
        lease_expires_at = null, updated_at = now(), completed_at = now()
    where idempotency_key = p_idempotency_key
      and request_hash = p_request_hash and status = 'pending'
  returning true;
$$;

create or replace function public.fail_ai_generation_job(
  p_idempotency_key text,
  p_request_hash text,
  p_error_code text
) returns boolean
language sql
security definer
set search_path = public
as $$
  update public.ai_generation_jobs
    set status = 'failed', result = null, error_code = left(p_error_code, 100),
        lease_expires_at = null, updated_at = now(), completed_at = now()
    where idempotency_key = p_idempotency_key
      and request_hash = p_request_hash and status = 'pending'
  returning true;
$$;

revoke all on table public.ai_generation_jobs from public, anon, authenticated;
revoke all on table public.ai_rate_limit_events from public, anon, authenticated;
revoke all on function public.acquire_ai_generation_job(text,text,text,text,text,integer,integer,integer,integer,integer,integer,integer,integer,integer) from public, anon, authenticated;
revoke all on function public.complete_ai_generation_job(text,text,jsonb) from public, anon, authenticated;
revoke all on function public.fail_ai_generation_job(text,text,text) from public, anon, authenticated;
grant execute on function public.acquire_ai_generation_job(text,text,text,text,text,integer,integer,integer,integer,integer,integer,integer,integer,integer) to service_role;
grant execute on function public.complete_ai_generation_job(text,text,jsonb) to service_role;
grant execute on function public.fail_ai_generation_job(text,text,text) to service_role;

-- Event rows are operational data, not permanent analytics.
-- Schedule this statement daily with Supabase Cron if pg_cron is enabled:
-- delete from public.ai_rate_limit_events where created_at < now() - interval '2 days';
-- delete from public.ai_generation_jobs where updated_at < now() - interval '7 days';
