create table if not exists public.soul_trace_profiles (
  user_email text primary key,
  pet_name text not null,
  personality_type text not null,
  generated_letter text not null,
  preferred_scenery text not null,
  hero_image_url text
);

create table if not exists public.soul_trace_answers (
  id bigint generated by default as identity primary key,
  user_email text not null references public.soul_trace_profiles (user_email) on delete cascade,
  answer_order int not null check (answer_order between 1 and 5),
  question text not null,
  answer text not null,
  unique (user_email, answer_order)
);

create index if not exists idx_soul_trace_answers_user_email
  on public.soul_trace_answers (user_email);
