"use client";
import { useLocale } from "@/components/locale-provider";
import { ArrowRightIcon } from "./icons";
import { Reveal } from "./reveal";

export function LetterPreview() {
  const { lang, t } = useLocale();
  const display = lang === "ko" ? "font-ko break-keep" : "font-display-en !tracking-normal";
  return <section className="relative overflow-hidden bg-[#1a1512] py-20 text-[#f8f2e7] md:py-28"><div className="pointer-events-none absolute left-1/2 top-1/2 size-[500px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#c8a24a]/10 blur-[130px]" /><div className="relative mx-auto grid max-w-6xl grid-cols-1 items-center gap-12 px-5 sm:px-8 lg:grid-cols-2"><div className="min-w-0"><Reveal><p className="mb-4 text-xs uppercase tracking-[0.28em] text-[#c8a24a]">{t("homepage.letter.label")}</p></Reveal><Reveal delay={80}><h2 className={`${display} text-3xl font-light leading-tight sm:text-5xl`}>{t("homepage.letter.title")}</h2></Reveal><Reveal delay={160}><p className={`${display} mt-5 max-w-md text-base leading-relaxed text-[#f8f2e7]/70`}>{t("homepage.letter.body")}</p></Reveal><Reveal delay={220}><div className="mt-9 space-y-4"><div className="rounded-xl border border-white/10 bg-black/25 p-4"><p className="text-[0.7rem] uppercase tracking-[0.22em] text-white/40">{t("homepage.letter.memoryLabel")}</p><p className={`${display} mt-1.5 text-sm text-white/80`}>{t("homepage.letter.memoryText")}</p></div><div className="flex justify-center"><ArrowRightIcon className="size-5 rotate-90 text-[#c8a24a]" /></div><div className="rounded-xl border border-[#c8a24a]/25 bg-[#c8a24a]/5 p-4"><p className="text-[0.7rem] uppercase tracking-[0.22em] text-[#c8a24a]">{t("homepage.letter.letterLabel")}</p><p className={`${display} mt-1.5 text-base italic text-white/90`}>{t("homepage.letter.letterText")}</p></div></div></Reveal></div><Reveal delay={140} className="flex justify-center"><div className="relative w-full max-w-sm rotate-1 rounded-sm bg-[#f3ebda] p-8 text-[#1a1512] shadow-2xl transition-transform duration-500 hover:rotate-0 sm:p-10"><div className="absolute right-6 top-6 h-14 w-11 rounded-sm border border-[#c8a24a]/40 bg-[#c8a24a]/10 text-center"><span className="mt-3 block text-[0.6rem] uppercase leading-tight tracking-[0.15em] text-[#c8a24a]">Soul<br />Trace</span></div><p className={`${display} pr-14 text-2xl`}>{t("homepage.letter.paperName")}</p><div className={`${display} mt-5 space-y-3 text-lg leading-relaxed text-[#1a1512]/85`}><p>{t("homepage.letter.letterText")}</p><p className="text-[#1a1512]/60">{t("homepage.hero.cardLine")}</p></div><p className={`${display} mt-8 text-base italic text-[#1a1512]/70`}>{t("homepage.letter.paperFrom")}</p><div className="mt-6 h-px bg-black/10" /><p className="font-display-en mt-4 text-[0.65rem] uppercase !tracking-[0.25em] text-[#c8a24a]">Soul Trace</p></div></Reveal></div></section>;
}
